"""Update barcode field to 13 characters

Revision ID: 3b752c65527f
Revises: 55a0464a420f
Create Date: 2024-10-04 21:22:55.133747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b752c65527f'
down_revision = '55a0464a420f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('barcode',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('barcode',
               existing_type=sa.String(length=13),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
