"""Add barcode field to Item model

Revision ID: 55a0464a420f
Revises: 2ddb8bd1c46d
Create Date: 2024-10-04 21:17:04.009326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a0464a420f'
down_revision = '2ddb8bd1c46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['barcode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###
