"""Add initial_quantity to Item model

Revision ID: e8ae0ad0e339
Revises: 3b752c65527f
Create Date: 2024-10-04 21:46:36.422246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ae0ad0e339'
down_revision = '3b752c65527f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('initial_quantity')

    # ### end Alembic commands ###
